### ISSUE TITLE
3ra vez que repito el ejercio

### ISSUE THREAD

**Issue by magdalenaviloriac** [maestria-geotel-201902/unidad-0-asignacion-1-asig-conrstudio-issues-magdalenaviloriac#2]
@geofis repeticion del ejercicio de nuevo suspongo que debe de estar en mi cuenta aunque el primero lo realice durante la hora de clase no se porque salio en otra cuenta aun teniendolo en la  mia  aunque recuerdo que la compañera dijo que le había llegado un mensaje asu correo.

**Comment by geofis** [comment]
Correcto, ahora sí @magdalenaviloriac
